
server:
  port: 5000


#服务名
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      filter:
        remove-non-proxy-headers:
          headers:
            - dummy
      routes:
        - id:  cloud-provider-1
          # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: lb://cloud-provider-1
          predicates:
            # 重点！转发该路径！,/userapi/**,
            - Path=/cloudprovider1/*/*
          # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
          #而不是我们期望的去掉userapi，只保留**部分
          filters:
            - StripPrefix=1
        - id:  cloud-provider-2
          uri: lb://cloud-provider-2
          predicates:
            - Path=/cloudprovider2/*/*
          filters:
            - StripPrefix=1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
